---
title: 'Pretest Results: CIG Hydrolytic Extracelleular Enzyme Assays'
author: "Hava Blair"
date: "July 1, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(glue)
library(ggrepel)
```

# Pre-test Data 

Pre-test data was processed with the R-Markdown document "eea_pretest_calcs.Rmd"


```{r data}
pre_data <- read.csv("./calcs/pretest_eea_2020-07-01.csv", stringsAsFactors = FALSE)

colnames(pre_data)
```

## Graphs



```{r graphs}
# B Enzyme
pre_data %>% 
  filter(enzyme == "BG") %>% 
  ggplot() +
  geom_point(aes(x = conc_uM, y = activity, color = sample_id)) + 
  facet_grid(cols = vars(ph_buffer), labeller = label_both) + 
  theme(legend.position = "bottom") + 
  labs(title = "4-MUB-B-glucopyranoside activity as a function of substrate concentration")

#C Enzyme 
pre_data %>% 
  filter(enzyme == "Cello") %>% 
  ggplot() +
  geom_point(aes(x = conc_uM, y = activity, color = sample_id)) + 
  facet_grid(cols = vars(ph_buffer), labeller = label_both) + 
  theme(legend.position = "bottom") + 
  labs(title = "4-MUB-cellobioside activity as a function of substrate concentration")

#N Enzyme 
pre_data %>% 
  filter(enzyme == "NAG") %>% 
  ggplot() +
  geom_point(aes(x = conc_uM, y = activity, color = sample_id)) + 
  facet_grid(cols = vars(ph_buffer), labeller = label_both) + 
  theme(legend.position = "bottom") + 
  labs(title = "4-MUB-N-acetyl_B-glucosaminide activity as a function of substrate concentration")

#P Enzyme 
pre_data %>% 
  filter(enzyme == "P") %>% 
  ggplot() +
  geom_point(aes(x = conc_uM, y = activity, color = sample_id)) + 
  facet_grid(cols = vars(ph_buffer), labeller = label_both) + 
  theme(legend.position = "bottom") + 
  labs(title = "4-MUB-phosphate activity as a function of substrate concentration")
```

# Graphs - buffer comparison 

```{r}

#P Enzyme 
pre_data %>% 
  filter(enzyme == "P" & sample_id == "RRV3_SH_B") %>% 
  ggplot() +
  geom_point(aes(x = conc_uM, y = activity, fill = ph_buffer)) + 
  theme(legend.position = "bottom") + 
  labs(title = "4-MUB-phosphate activity as a function of substrate concentration") 
  

```



